apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: empms-db
  labels:
    app: empms-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-db
  template:
    metadata:
      labels:
        app: empms-db
    spec:
      containers:
      - name: empms-db
        image: opstree/empms-db:1.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "attendancedb"
