apiVersion: v1
kind: Pod
metadata:
  name: empms-attendance
spec:
  initContainers:
  - name: init-mysql
    image: busybox:1.28
    imagePullPolicy: Always
    command: ['sh', '-c', 'echo The app is running! && sleep 20']
  containers:
  - name: attendance
    image: opstree/empms-attendance:1.0
  restartPolicy: Always
