---
kind: Service
apiVersion: v1
metadata:
  name: empms-webserver
spec:
  type: LoadBalancer
  selector:
    app: empms-webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
