apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: stark-industry
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 1500Mi
    pods: "10"
